[package]
name = "rust-s3"
version = "0.2.4"
authors = ["Drazen Urch"]
description = "Tiny Rust library for working with Amazon S3."
repository = "https://github.com/durch/rust-s3"
readme = "README.md"
keywords = ["Amazon", "AWS", "S3"]
license = "MIT"
documentation = "https://durch.github.io/rust-s3/"

[lib]
name = "s3"
path = "src/lib.rs"

[dependencies]
openssl = "0.7.14"
time = "0.1.35"
curl = "0.3.0"
rustc-serialize = "0.3.19"
url = "1.1.1"
log = '0.3.6'
