[package]
name = "rust-s3"
version = "0.8.0"
authors = ["Drazen Urch", "Nick Stevens"]
description = "Tiny Rust library for working with Amazon S3."
repository = "https://github.com/durch/rust-s3"
readme = "README.md"
keywords = ["Amazon", "AWS", "S3"]
license = "MIT"
documentation = "https://durch.github.io/rust-s3/"

[lib]
name = "s3"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.0"
curl = "0.4.8"
error-chain = "0.10.0"
hex = "0.2.0"
hmac = "0.4.2"
serde_derive = "1.0.11"
serde = "1.0.11"
serde-xml-rs = "0.2.1"
sha2 = "0.6.0"
url = "1.5.1"

