[package]
name = "aws-creds"
version = "0.22.2"
authors = ["Drazen Urch"]
description = "Tiny Rust library for working with Amazon IAM credential,s, supports `s3` crate"
repository = "https://github.com/durch/rust-s3"
readme = "README.md"
keywords = ["AWS", "S3", "Wasabi", "Minio", "Yandex"]
license = "MIT"
documentation = "https://durch.github.io/rust-s3/"
edition = "2018"

[lib]
name = "awscreds"
path = "src/lib.rs"

[dependencies]
simpl = "0.1.0"
dirs = "2.0.2"
rust-ini = "0.15.2"
tokio = "0.2.20"
reqwest = {version = "0.10.4", features = ["json"]}

