[package]
name = "aws-creds"
version = "0.27.0"
authors = ["Drazen Urch"]
description = "Tiny Rust library for working with Amazon IAM credential,s, supports `s3` crate"
repository = "https://github.com/durch/rust-s3"
readme = "README.md"
keywords = ["AWS", "S3", "Wasabi", "Minio", "Yandex"]
license = "MIT"
documentation = "https://durch.github.io/rust-s3/"
edition = "2018"

[lib]
name = "awscreds"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0"
dirs = "4"
rust-ini = "0.17"
attohttpc = { version = "0.17", default-features = false, features = ["json"] }
url = "2"
serde-xml-rs = "0.5"
serde = "1"
serde_derive = "1"


[features]
default = ["native-tls"]
native-tls = ["attohttpc/tls"]
rustls-tls = ["attohttpc/tls-rustls"]

[dev-dependencies]
env_logger = "0.9"
